services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - SUPABASE_KEY=${PUBLIC_SUPABASE_ANON_KEY}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: npm run dev
