services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=http://supabase-rest:3000
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
    command: npm run dev

  supabase-db:
    image: supabase/postgres:15.1.0.91
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - supabase-db-volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  supabase-rest:
    image: postgrest/postgrest:v11.0.1
    depends_on:
      - supabase-db
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@10xtranslationsfactory-supabase-db-1:5432/${POSTGRES_DB}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "54340:3000"
    restart: unless-stopped

  supabase-auth:
    image: supabase/gotrue:v2.10.1
    depends_on:
      - supabase-db
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@10xtranslationsfactory-supabase-db-1:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_DB_MIGRATIONS_PATH: /usr/local/etc/gotrue/migrations
      GOTRUE_DB_AUTOMIGRATE: "true"
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9999
      GOTRUE_SMTP_ADMIN_EMAIL: bmankowski@gmail.com
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_LOG_LEVEL: debug
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "false"
      GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
      GOTRUE_SMTP_HOST: ""
      GOTRUE_SMTP_PORT: "25"
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_SENDER_NAME: "GoTrue"
      API_EXTERNAL_URL: http://localhost:54341
    ports:
      - "54341:9999"
    restart: unless-stopped

volumes:
  supabase-db-volume:
