[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "20"

# Jeśli używasz SSR (opcja 2), użyj tego zamiast powyższego:
# [build]
#   command = "npm run build:netlify"
#   publish = "dist"

# Obsługa SPA routing - tylko dla stron, nie dla API
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 